# Generated by Django 4.1.6 on 2023-02-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
