# Generated by Django 4.1.6 on 2023-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_form_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='gender',
            new_name='female',
        ),
        migrations.AddField(
            model_name='form',
            name='male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
