# Generated by Django 4.1.6 on 2023-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_rename_gender_form_female_form_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='female',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='form',
            name='male',
        ),
    ]
