# Generated by Django 4.1.6 on 2023-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_form_cgpa1_form_cgpa2_form_coc1_form_coc2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='martyr_lineage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
