# Generated by Django 4.1.6 on 2023-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_alter_form_martyr_lineage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='emergency_contact_father',
            new_name='eemergency',
        ),
        migrations.RemoveField(
            model_name='form',
            name='emergency_contact_mother',
        ),
        migrations.AlterField(
            model_name='form',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
