# Generated by Django 4.1.6 on 2023-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0009_form_eemergencycontatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
