# Generated by Django 4.1.6 on 2023-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0010_alter_form_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='completionyr2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='enrollmentyr2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
