# Generated by Django 4.1.6 on 2023-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0011_alter_form_completionyr2_alter_form_enrollmentyr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='coc1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
