# Generated by Django 4.1.6 on 2023-02-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0012_alter_form_coc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='cgpa1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
