# Generated by Django 4.1.6 on 2023-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0013_alter_form_cgpa1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
