# Generated by Django 4.1.6 on 2023-02-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0014_alter_form_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='eemergency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='father_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
