# Generated by Django 4.1.6 on 2023-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0015_alter_form_eemergency_alter_form_father_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='bank_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='house_no_d',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='ward_no_d',
            field=models.BigIntegerField(),
        ),
    ]
