# Generated by Django 4.1.6 on 2023-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0016_alter_form_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='cit_att',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
