# Generated by Django 4.1.6 on 2023-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0017_form_cit_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='coc2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
